name: Deploy Portfolio Website

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Build project
        run: |
          npm ci
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.FRONTEND_DEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get parameters from SSM
        run: |
          S3_BUCKET=$(aws ssm get-parameter --name "/infra/prod/s3/bucket_name" --query "Parameter.Value" --output text)
          CF_DISTRIBUTION_ID=$(aws ssm get-parameter --name "/infra/prod/cloudfront/distribution_id" --query "Parameter.Value" --output text)
          CLOUDFLARE_ZONE_ID=$(aws ssm get-parameter --name "/infra/prod/cloudflare/cloudflare_zone_id" --with-decryption --query "Parameter.Value" --output text)
          CLOUDFLARE_CACHE_API_TOKEN=$(aws ssm get-parameter --name "/infra/prod/cloudflare/cache_api_token" --with-decryption --query "Parameter.Value" --output text)
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
          echo "CF_DISTRIBUTION_ID=$CF_DISTRIBUTION_ID" >> $GITHUB_ENV
          echo "CLOUDFLARE_ZONE_ID=$CLOUDFLARE_ZONE_ID" >> $GITHUB_ENV
          echo "CLOUDFLARE_CACHE_API_TOKEN=$CLOUDFLARE_CACHE_API_TOKEN" >> $GITHUB_ENV

      - name: Sync with S3
        run: |
          aws s3 sync ./dist s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CF_DISTRIBUTION_ID }} --paths "/*"

      - name: Purge CloudFlare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ env.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ env.CLOUDFLARE_CACHE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
